[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/",
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/src/",
    "@uniswap/permit2/=lib/permit2/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v3-core/=lib/v3-core/",
]

solc_version = "0.8.26"
evm_version = "cancun"
ffi = true

viaIR = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
